### ISSUE TITLE
error when installing with install.js 

### ISSUE THREAD

**Issue by jjwong0915** [notablemind/jupyter-nodejs#17]
Here is the error message:

``` shell
j@j-K401LB:~/Downloads/jupyter-nodejs-1.1.0/package$ node install.js
fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/home/j/.ipython/kernels/nodejs/kernel.json'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at Object.<anonymous> (/home/j/Downloads/jupyter-nodejs-1.1.0/package/install.js:15:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

Making the missing directory manully seems able to avoid the poblem:

``` shell
mkdir -p ~/.ipython/kernels/nodejs/
```

**Comment by terraqout** [comment]
so why don't you make PR?

**Comment by timshephard** [comment]
@jjwong0915 thx, that fixed it.

**Comment by steven-collins-omega** [comment]
Something strange happened with this commit 8acf996d47bf322908175e0ceb4858224fe8238c by @jjwong0915 -- I can see it in GitHub itself, but it's not merged into master, it's not reachable from any branch or tag, and it doesn't seem to get pulled down at all when I clone or fork the repo. Could it please be merged into master? Thanks.

**Comment by jjwong0915** [comment]
#22 
And I found that [b0d7c7b](https://github.com/notablemind/jupyter-nodejs/commit/b0d7c7b83db9ab3463b319e116de18d777591796) has fixed the problem, but the [latest release](https://github.com/notablemind/jupyter-nodejs/releases/tag/v1.1.0) doesn't include that commit. Should it released a new patch?
