### ISSUE TITLE
Get " ‘Use’ is not a member of ‘node::Buffer’" when install 

### ISSUE THREAD

**Issue by xmduhan** [notablemind/jupyter-nodejs#18]
## When I use "npm install && node install.js" to install jupyter-nodejs,I get a Error say this:

... ... ... ... ... ... ... ...
../node_modules/nan/nan.h:683:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
make: **\* [Release/obj.target/contextify/src/contextify.o] 错误 1
make:离开目录“/home/duhan/.jupyter/jupyter-nodejs/node_modules/contextify/build”
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/duhan/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-61-generic
gyp ERR! command "/home/duhan/.nvm/versions/node/v4.1.2/bin/node" "/home/duhan/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/duhan/.jupyter/jupyter-nodejs/node_modules/contextify
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 3.13.0-61-generic
npm ERR! argv "/home/duhan/.nvm/versions/node/v4.1.2/bin/node" "/home/duhan/.nvm/versions/node/v4.1.2/bin/npm" "install"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
## npm ERR!     /home/duhan/.jupyter/jupyter-nodejs/npm-debug.log

How can I do to pass the install??

**Comment by jaredly** [comment]
I just fixed this, by removing the contextify dependency
