### ISSUE TITLE
Display html, using %html magic (or some other way)

### ISSUE THREAD

**Issue by haakenlid** [notablemind/jupyter-nodejs#21]
I want to use the %html magic from ipython, but it seems to not exist in this kernel. And there's not list magics either (see #8). I want to use a node script that generates html, and then display it in the output cell. Is there any other way to achieve this, except magice.

**Comment by jasonphillips** [comment]
I found a relatively simple way to implement HTML output, see my gist here:

https://gist.github.com/jasonphillips/3ecfc221f8f931027c82511870727e34

It's not secure (no checking for dangerous content in the HTML, etc) but that isn't necessary for my local development purposes.

**Comment by haakenlid** [comment]
There's another way to display html as well. The function `display()` which isn't documented in the readme, but is mentioned in issue #4 takes an optional mimetype argument. So displaying html is actually built in already.

    display("<h1>Hello World</h1>", "text/html") 

Combined with react-dom-render you can display jsx like this:

    %%babel
    const React = require('react')
    const ReactDOM = require('react-dom/server')
    const renderJsx = jsx => display(ReactDOM.renderToStaticMarkup(jsx), 'text/html')
    renderJsx(<h1>Hello World!</h1>)

**Comment by haakenlid** [comment]
My problem is solved. But I think it would be nice to mention the `display()` function in the main readme.

**Comment by liuderchi** [comment]
Big thanks for your tips @haakenlid @jasonphillips 💯
