### ISSUE TITLE
require/import packages

### ISSUE THREAD

**Issue by Simobain** [notablemind/jupyter-nodejs#26]
Where should I install packages to be accessible by my nodejs kernel ? I don't see any node_modules folder.

**Comment by sumukh-ramprasad** [comment]
@Simobain Did you figure it out?

**Comment by jaredly** [comment]
there's not a super good solution to this atm :/ the kernel's `cwd` ends up being wherever you started your jupyter process from, which isn't the best. I'd probably like for there to just be a global `~/.jupyter-nodejs` folder or something where modules are installed.
Do you have any thoughts?

**Comment by Simobain** [comment]
I agree it would be better to have a "special" node_modules repo for the node js kernel.

And yes i figured out, sorry for the long time without seeing my notification and then your answers ;) !
