### ISSUE TITLE
require relative paths

### ISSUE THREAD

**Issue by ricardofbarros** [notablemind/jupyter-nodejs#3]
I'm using atom with [hydrogen plugin](https://github.com/willwhitney/hydrogen), basically is jupyter for the text editor and I have installed your package successfully and everything is working just fine.

![screen shot 2015-05-27 at 15 17 20](https://cloud.githubusercontent.com/assets/6867996/7838386/7df1a8be-0484-11e5-8cfc-58788bd5d415.png)

The problem now is with require for relative paths, which I guess ipython won't know the PATH I'm on and wont pass it to node, does any one know a workaround for this?

```js
var test = require('./test');
```

Error: Cannot find module './test'
at Function.Module._resolveFilename (module.js:336:15)
at Function.Module._load (module.js:278:25)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object.Contextify.sandbox.run (/Users/rbarros/package/node_modules/contextify/lib/contextify.js:12:24)
at Context.rawRun (/Users/rbarros/package/build/context.js:105:23)
at Context.rawEvaluate (/Users/rbarros/package/build/context.js:117:23)
at Context.execute (/Users/rbarros/package/build/context.js:194:21)
at Kernel.executeRequest (/Users/rbarros/package/build/kernel.js:153:16)
at Kernel.onShell (/Users/rbarros/package/build/kernel.js:90:14) Runtime error
Cannot find module './test'

**Comment by jaredly** [comment]
In `ipython` shell, you can type `!pwd` to get the current working directory (or `!some shell cmd` for any shell command), and `cd somepath` (without the `!`) to change the current working directory of the jupyter kernel.
I'm not sure how hydrogen would be able to automatically communicate this for you... but at least this should work for the moment. I assume those same commands should work in your atom shell.

**Comment by ricardofbarros** [comment]
I don't know if this is normal but running `ipython console --kernel nodejs`and sending the command !pwd  gives me an error.

```
ReferenceError: pwd is not defined
    at <anonymous>:1:2
```

But if I run ipython with the default kernel `ipython console`, the shell commands works just fine.

**Comment by jaredly** [comment]
Oh! Looks like the !shell stuff was done after the latest release. I just
published v1.1.0
<https://github.com/notablemind/jupyter-nodejs/releases/tag/v1.1.0>, which
should get things working for you.

**Comment by ricardofbarros** [comment]
Still I don't think this will resolve the issue by having the possibility to inject shell commands, I think the problem is more deeper than we think it is. Could yoy explain me briefly how do your kernel recieves stdin (node code) and executes it? File and line number would be awesome :smile:

**Comment by ricardofbarros** [comment]
lib/context.js shell function, am I close?

**Comment by ricardofbarros** [comment]
Now the problem resides on the Atom framework.
