### ISSUE TITLE
Immediately rejected Promise kills the kernel

### ISSUE THREAD

**Issue by obogobo** [notablemind/jupyter-nodejs#38]
Hi there, loving the kernel so far! It works great with Node6 and has made presentations a breeze.

One small snag, despite best efforts catching Promise rejections, the kernel seems to die unless a setTimeout is involved. Examples!

this works:
```
var getHamburgerMaybe = new Promise((resolve, reject) => {
    setTimeout(() => reject("[OutOfMeatException] Where's the beef?"), 3000);
});

getHamburgerMaybe.catch(error => console.log(error));
```

this kills the kernel:
```
const p = new Promise((resolve, reject) => {
    reject();
})
.then(
    () => {
        console.log('Promise fulfilled.');
    },
    () => {
        console.log('Promise rejected');
    }
)
```

Any thoughts?

**Comment by jaredly** [comment]
I just upgraded to use `vm` instead of contextify, and it looks like this is working now?

**Comment by sortuniq** [comment]
Ahh great, it works now! Thanks for looking into it 👍

**Comment by obogobo** [comment]
Ahh great, it works now! Thanks for looking into this 👍
