### ISSUE TITLE
No longer builds due to a problem in the contextify dependency

### ISSUE THREAD

**Issue by ResidentMario** [notablemind/jupyter-nodejs#40]
See this issue: https://github.com/brianmcd/contextify/issues/212.

Since `contextify` is deprecated, how hard would it be to move this over to its replacement Node-native `vm` module?

**Comment by ResidentMario** [comment]
More information: the error occurs at `npm install && node install.js`, and the text is:

    npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
    npm ERR! Exit status 1

**Comment by jsnelgro** [comment]
has anybody come up with a workaround for the time being?

**Comment by jaredly** [comment]
I just dropped the contextify dep, and moved over to the `vm` module. The only downside is that `vm` doesn't give us access to the `global` object, so completions on built-in variables are a bit more limited. but other than that, we're all set!
install jupyter-nodejs@2.0.0 and let me know how it goes!

**Comment by jsnelgro** [comment]
@jaredly up and running! Awesome!
