### ISSUE TITLE
Not sure if jupyter-nodejs is working properly...

### ISSUE THREAD

**Issue by kalmdown** [notablemind/jupyter-nodejs#41]
Very new to development so sorry if this issue is handled by another component but I Googled the warning and couldn't find anything. 

**When I run the hello world test I receive:**
In [1]: console.log('hello jupyter')Unknown message type:  is_complete_request
[0]: 04334cdb-c25c-4148-a0e1-e70132136aba
[1]: <IDS|MSG>
[2]: 53570768fbac2a21f09927961431f7f42aa9e597b371fe41ebbf7e8c89389d7f
[3]: {"version":"5.0","date":"2017-02-20T18:49:54.022945","session":"04334cdb-c25c-4148-a0e1-e70132136aba","user
[4]: {}
[5]: {}
[6]: {"code":"console.log('hello jupyter')"}
/Users/212316291/anaconda/lib/python3.6/site-packages/jupyter_console/ptshell.py:571: UserWarning: The kernel di
  warn('The kernel did not respond to an is_complete_request. '
In [1]: console.log('hello jupyter')
hello jupyter

When I ran "npm install && node install.js" line I get the following warning: 
npm WARN package.json Dependency 'mkdirp' exists in both dependencies and devDependencies, using 'mkdirp@^0.5.1' from dependencies

**Which and Version**
/Users/212316291/jupyter-nodejs
==> which npm
/Users/212316291/anaconda/bin/npm

/Users/212316291/jupyter-nodejs
==> npm --version
2.14.12

**My current kernel.json**
{
  "argv": [
    "node",
    "/Users/212316291/jupyter-nodejs/build/run.js",
    "{connection_file}"
  ],
  "display_name": "NodeJS",
  "language": "javascript"
}

**Comment by jaredly** [comment]
I just added support for `is_complete_request`, thanks for the notice!
