### ISSUE TITLE
!cd is not changing pwd...

### ISSUE THREAD

**Issue by Panoplos** [notablemind/jupyter-nodejs#9]
iPython @ 4.0.0-dev

See here:

![screen shot 2015-06-26 at 7 52 10 pm](https://cloud.githubusercontent.com/assets/2549985/8375939/e3dded5c-1c3c-11e5-917f-b58a1e01e543.png)

**Comment by rcompton** [comment]
+1

**Comment by slavaGanzin** [comment]
node can't change pwd, its not an issue
